### ISSUE TITLE
Warning: "Old package separator ' deprecated"

### ISSUE THREAD

**Issue by rwp0** [schwern/Carp-Assert#3]
Getting the below warning importing `Carp::Assert` via [Pithub](https://metacpan.org/dist/Pithub):

```sh
/usr/bin/perlbrew \
  exec -q \
  --with blead \
  /home/regular/perl5/perlbrew/perls/blead/bin/perl5.37.9 \
  /home/regular/bin/pithub
```

```
Old package separator "'" deprecated at
  /home/regular/perl5/perlbrew/perls/blead/lib/site_perl/5.37.9/Carp/Assert.pm
  line 396.
```

Maybe it's time to start removing `'` from `shouldn't` function in [line 396](https://github.com/schwern/Carp-Assert/blob/master/lib/Carp/Assert.pm#L396):

```perl
sub shouldn't ($$) {     # emacs cperl-mode madness #' sub {
    my $env_ndebug = exists $ENV{PERL_NDEBUG} ? $ENV{PERL_NDEBUG}
                                              : $ENV{'NDEBUG'};
    if( $env_ndebug ) {
        return undef;
    }
    else {
        shouldnt($_[0], $_[1]);
    }
}
```

---

https://github.com/schwern/Carp-Assert/blob/af33480a7d1a36a5d5da6fa952cd0767afc1be40/lib/Carp/Assert.pm#L396

**Comment by demerphq** [comment]
Fixed by https://github.com/schwern/Carp-Assert/pull/4
